#!/bin/sh

case "$1" in
  start)
        /bin/audioservice &
        printf "start audioservice"
        ;;
  stop)
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
